services:
  backend:
    build: ./backend
    mem_limit: 512m
    cpus: 1.0
    networks:
      - frontend
      - backend
    environment:
      APP_NAME: "${APP_NAME}"
      APP_VERSION: "${APP_VERSION}"
      APP_ENVIRONMENT: "${APP_ENVIRONMENT}"
      BACKEND_PORT: "${BACKEND_PORT}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${POSTGRES_DB}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_USER: "${POSTGRES_USER}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      retries: 3
      timeout: 5s
      start_period: 5s

  web:
    image: nginx:latest
    mem_limit: 512m
    cpus: 1.0
    networks: [frontend]
    restart: always
    ports:
      - "${NGINX_HOST_PORT}:80"
    depends_on:
      backend:
        condition: service_healthy
      db:
        condition: service_started
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  db:
    image: postgres:16
    mem_limit: 512m
    cpus: 1.0
    networks: [backend]
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - content:/var/lib/postgresql/data

  redis:
    image: redis:8.2.3
    networks: [backend]
    mem_limit: 256m
    cpus: 0.5

volumes:
  content:

networks:
  frontend:
  backend:
